version: '3.8'

services:
  
  app:
    build: .
    ports:
      - "3000:8080" 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/a3
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db  
    networks:
      - minha-rede  

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DATABASE: meu_banco         
    ports:
      - "3306:3306"  
    volumes:
      - mysql-data:/var/lib/mysql  
      - ./init-scripts:/docker-entrypoint-initdb.d  

    networks:
      - minha-rede  

volumes:
  mysql-data:

networks:
  minha-rede:
    driver: bridge  
